# Generated by Django 4.2.9 on 2025-02-12 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_dj', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VRDJSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_type', models.CharField(choices=[('club', 'Night Club'), ('festival', 'Festival Stage'), ('studio', 'Professional Studio'), ('custom', 'Custom Environment')], default='club', max_length=20)),
                ('is_collaborative', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vr_session', to='ai_dj.aidjsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vr_dj_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VRDJInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('deck_manipulation', 'Deck Manipulation'), ('effect_trigger', 'Effect Trigger'), ('environment_change', 'Environment Change'), ('ai_suggestion_response', 'AI Suggestion Response')], max_length=30)),
                ('details', models.JSONField()),
                ('success_rating', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='vr_dj.vrdjsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VRDJEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scene_data', models.JSONField()),
                ('lighting_preset', models.CharField(choices=[('ambient', 'Ambient'), ('dynamic', 'Dynamic'), ('reactive', 'Music Reactive'), ('custom', 'Custom')], default='dynamic', max_length=20)),
                ('crowd_simulation', models.BooleanField(default=True)),
                ('visual_effects', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='vr_dj.vrdjsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VRDJControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_type', models.CharField(choices=[('turntable_left', 'Left Turntable'), ('turntable_right', 'Right Turntable'), ('crossfader', 'Crossfader'), ('eq_high', 'High EQ'), ('eq_mid', 'Mid EQ'), ('eq_low', 'Low EQ'), ('effect', 'Effect Control')], max_length=30)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='vr_dj.vrdjsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
