# Generated by Django 4.2.9 on 2025-02-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='multiusercomposite',
            name='idx_multi_user_comp',
        ),
        migrations.AddIndex(
            model_name='multiusercomposite',
            index=models.Index(fields=['created_at'], name='idx_multi_user_comp'),
        ),
    ]
