# urls.py for ai_dj
# This file defines the URL patterns for the ai_dj app.

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import TrackViewSet, AIDJSessionViewSet, AIDJPlayHistoryViewSet, AIDJRecommendationViewSet, AIDJFeedbackViewSet, AIDJSavedSetViewSet
# Removing tenants import as it's not needed
# from tenants.routers import TenantAwareRouter

AI_DJ_MODULE = 'ai_dj'

router = DefaultRouter()  # Using DefaultRouter instead of TenantAwareRouter
router.register(r'tracks', TrackViewSet, basename='track')
router.register(r'sessions', AIDJSessionViewSet, basename='session')
router.register(r'play-history', AIDJPlayHistoryViewSet, basename='playhistory')
router.register(r'recommendations', AIDJRecommendationViewSet, basename='recommendation')
router.register(r'feedback', AIDJFeedbackViewSet, basename='feedback')
router.register(r'saved-sets', AIDJSavedSetViewSet, basename='savedset')

# Additional URL patterns for voice command processing and other features
additional_patterns = [
    path('sessions/<int:pk>/process-voice-command/', 
         AIDJSessionViewSet.as_view({'post': 'process_voice_command'}), 
         name='process-voice-command'),
    path('dj-personas/', include('ai_dj.modules.dj_personas.urls')),
    path('hybrid-dj/', include('ai_dj.modules.hybrid_dj.urls')),
]

urlpatterns = router.urls + additional_patterns

# The following URL patterns are automatically generated by the router:
# /api/tracks/ - List all tracks or create a new one
# /api/tracks/<pk>/ - Retrieve, update or delete a track
# /api/tracks/<pk>/lyrics/ - Get track lyrics in specified language
# /api/tracks/<pk>/translations/ - Get all available translations for a track
# /api/tracks/<pk>/add_translation/ - Add a new translation for a track
# /api/tracks/<pk>/add_lyrics/ - Add lyrics for a track in a specific language
