# Generated by Django 4.2.9 on 2025-02-12 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_dj', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionalJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_minutes', models.IntegerField()),
                ('is_public', models.BooleanField(default=False)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emotional Journey',
                'verbose_name_plural': 'Emotional Journeys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('valence', models.FloatField(help_text='Emotional positivity/negativity (-1 to 1)')),
                ('arousal', models.FloatField(help_text='Emotional intensity/energy (0 to 1)')),
                ('color_code', models.CharField(help_text='Hex color code', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emotional State',
                'verbose_name_plural': 'Emotional States',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JourneyWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('transition_type', models.CharField(max_length=50)),
                ('intensity', models.FloatField(help_text='Intensity of the emotional state (0 to 1)')),
                ('parameters', models.JSONField(default=dict)),
                ('emotional_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotional_journey.emotionalstate')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotional_journey.emotionaljourney')),
            ],
            options={
                'verbose_name': 'Journey Waypoint',
                'verbose_name_plural': 'Journey Waypoints',
                'ordering': ['journey', 'position'],
                'unique_together': {('journey', 'position')},
            },
        ),
        migrations.CreateModel(
            name='SessionJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('progress', models.FloatField(default=0.0)),
                ('status', models.CharField(max_length=50)),
                ('current_waypoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emotional_journey.journeywaypoint')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotional_journey.emotionaljourney')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_dj.aidjsession')),
            ],
            options={
                'verbose_name': 'Session Journey',
                'verbose_name_plural': 'Session Journeys',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='JourneyFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('feedback_text', models.TextField(blank=True)),
                ('emotional_impact', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotional_journey.sessionjourney')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journey Feedback',
                'verbose_name_plural': 'Journey Feedbacks',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmotionalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('intensity', models.FloatField()),
                ('confidence_score', models.FloatField()),
                ('source_data', models.JSONField(default=dict)),
                ('emotional_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotional_journey.emotionalstate')),
                ('session_journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotional_journey.sessionjourney')),
            ],
            options={
                'verbose_name': 'Emotional Snapshot',
                'verbose_name_plural': 'Emotional Snapshots',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmotionalAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.CharField(max_length=50)),
                ('usage_count', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('emotional_impact_data', models.JSONField(default=dict)),
                ('user_demographics', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotional_journey.emotionaljourney')),
            ],
            options={
                'verbose_name': 'Emotional Analytics',
                'verbose_name_plural': 'Emotional Analytics',
                'ordering': ['-generated_at'],
                'unique_together': {('journey', 'time_period', 'generated_at')},
            },
        ),
    ]
