# Generated by Django 5.0.6 on 2025-10-21 07:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ai_music_generation",
            "0002_abtest_cocreationsession_genreblend_transitionpoint_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aimusicrequest",
            name="duration",
            field=models.IntegerField(
                blank=True,
                help_text="Duration of the track in seconds",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(15),
                    django.core.validators.MaxValueValidator(600),
                ],
                verbose_name="Duration (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="aimusicrequest",
            name="format",
            field=models.CharField(
                default="mp3",
                help_text="Output audio format (mp3, wav, stems)",
                max_length=10,
                verbose_name="Output Format",
            ),
        ),
        migrations.AddField(
            model_name="aimusicrequest",
            name="mood",
            field=models.CharField(
                blank=True,
                help_text="Mood of the music",
                max_length=100,
                null=True,
                verbose_name="Mood",
            ),
        ),
        migrations.AddField(
            model_name="aimusicrequest",
            name="style",
            field=models.CharField(
                blank=True,
                help_text="Music style or genre",
                max_length=100,
                null=True,
                verbose_name="Style/Genre",
            ),
        ),
        migrations.AlterField(
            model_name="aimusicrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who made the request (null for anonymous requests)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_music_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
