# Generated by Django 4.2.9 on 2025-02-12 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_dj', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('effect_type', models.CharField(choices=[('filter', 'Filter Fade'), ('echo', 'Echo Out'), ('reverb', 'Reverb Trail'), ('cut', 'Hard Cut'), ('power_down', 'Power Down'), ('custom', 'Custom Effect Chain')], default='filter', max_length=20)),
                ('duration', models.FloatField(help_text='Duration in seconds')),
                ('effect_parameters', models.JSONField(default=dict, help_text='Effect-specific parameters')),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HumanDJPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_bpm_range_min', models.IntegerField(default=80)),
                ('preferred_bpm_range_max', models.IntegerField(default=160)),
                ('preferred_transition_length', models.FloatField(default=8.0, help_text='Default transition length in seconds')),
                ('auto_suggestions_enabled', models.BooleanField(default=True)),
                ('auto_transitions_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dj_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HumanDJAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('track_select', 'Track Selection'), ('transition_adjust', 'Transition Adjustment'), ('effect_adjust', 'Effect Adjustment'), ('suggestion_accept', 'Suggestion Accepted'), ('suggestion_reject', 'Suggestion Rejected')], max_length=20)),
                ('parameters', models.JSONField(default=dict, help_text='Action-specific parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_dj_actions', to='ai_dj.aidjsession')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_dj.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('next_track', 'Next Track'), ('transition', 'Transition Style'), ('effect', 'Effect Suggestion'), ('energy_level', 'Energy Level Change')], max_length=20)),
                ('confidence_score', models.FloatField(help_text='AI confidence in this recommendation (0-1)')),
                ('parameters', models.JSONField(default=dict, help_text='Recommendation-specific parameters')),
                ('was_accepted', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_as_current', to='ai_dj.track')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='ai_dj.aidjsession')),
                ('suggested_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_as_suggestion', to='ai_dj.track')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
