# Generated by Django 4.2.9 on 2025-02-12 21:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_dj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionalPlaylistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_mood', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('energetic', 'Energetic'), ('calm', 'Calm'), ('focused', 'Focused')], max_length=20)),
                ('description', models.TextField()),
                ('tempo_range_min', models.IntegerField(help_text='Minimum BPM', validators=[django.core.validators.MinValueValidator(0)])),
                ('tempo_range_max', models.IntegerField(help_text='Maximum BPM', validators=[django.core.validators.MinValueValidator(0)])),
                ('energy_level', models.FloatField(help_text='Target energy level', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('valence_level', models.FloatField(help_text='Target emotional positivity', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['target_mood', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VoiceEmotionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('neutral', 'Neutral'), ('excited', 'Excited'), ('calm', 'Calm'), ('frustrated', 'Frustrated')], max_length=20)),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('pitch', models.FloatField()),
                ('tempo', models.FloatField()),
                ('energy', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('valence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_dj.aidjsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmotionalMusicPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefer_mood_matching', models.BooleanField(default=True)),
                ('prefer_mood_improvement', models.BooleanField(default=True)),
                ('min_energy', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('max_energy', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('gradual_mood_transition', models.BooleanField(default=True)),
                ('transition_duration', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ai_dj.aidjsession')),
            ],
        ),
    ]
